config/routes.rb
Rails.application.routes.draw do

  # get 'errors/not_found'
  # get 'errors/internal_server_error'
  # get "/404" => "errors#not_found"
  # get "/500" => "errors#internal_server_error"

  resources :login_events

  resources :project_attachment_types

  resources :standards do
    collection { post :import }
  end

  resources :project_attachments

  resources :slider_objects

  resources :tags

  resources :types

  devise_for :users, controllers: { sessions: "users/sessions" }, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
    end

  resources :users

  root 'pages#home'

  match '/auth/:provider/callback', :to => 'sessions#callback', :via => [:get]

  resources :projects

  mathjax 'mathjax'

end

app/models/login_event.rb
class LoginEvent < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :type
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :standards
  has_many :project_attachments, dependent: :destroy
  has_many :project_fields, dependent: :destroy
  has_many :project_other_fields, dependent: :destroy
  has_many :slider_objects, dependent: :destroy
  belongs_to :user

  accepts_nested_attributes_for :project_attachments, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :project_fields, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :project_other_fields, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :slider_objects, allow_destroy: true, reject_if: :all_blank

  mount_uploader :featured_image, FeaturedImageUploader

  scope :publications, -> { where(status: STATUSES.index('Published')) }
  scope :drafts, -> { where(status: STATUSES.index('Draft')) }
  scope :pending_review, -> { where(status: STATUSES.index('Pending Review')) }

  STATUSES = ['Draft', 'Pending Review', 'Published']

  if Rails.env.development?
    searchable do
      text :name, :content, :author_name

      text :tags do
        tags.map { |tag| tag.name }
      end
    end
  else
    def search

    end
  end

end

app/models/project_attachment.rb
class ProjectAttachment < ActiveRecord::Base
  mount_uploader :resource, ResourceUploader

  belongs_to :project
  belongs_to :project_attachment_type

  before_save :default_name
  # before_validation :mark_for_destruction

  def default_name
    self.file_name = File.basename(resource.file.path, '.*').gsub("_", " ")
  end

  def mark_for_removal
    unless resource
      mark_for_destruction
    end
  end
end

app/models/project_field.rb
class ProjectField < ActiveRecord::Base
  belongs_to :project

  TYPES = ["DETAILS" , "OTHER"]
end

app/models/project_other_field.rb
class ProjectOtherField < ActiveRecord::Base
end

app/models/slider_object.rb
class SliderObject < ActiveRecord::Base
  mount_uploader :resource, ResourceUploader

  belongs_to :project

  before_save :default_name

  def default_name
    self.file_name = File.basename(resource.file.path, '.*').gsub("_", " ") if resource.file
  end

  def mark_for_removal
    unless resource
      mark_for_destruction
    end
  end
end

app/models/slider_objects.rb
class SliderObject < ActiveRecord::Base
  mount_uploader :resource, ResourceUploader

  belongs_to :project
  before_save :default_name

  def default_name
    self.file_name = File.basename(resource.file.path, '.*').gsub("_", " ")
  end

  def mark_for_removal
    unless resource
      mark_for_destruction
    end
  end

end

app/models/standard.rb
class Standard < ActiveRecord::Base

  has_and_belongs_to_many :projects

  def code_and_category
    "#{code} - #{category}"
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      standard = find_by_id(row["id"]) || new
      standard.attributes = row.to_hash.slice(*attribute_names)
      standard.save!
    end
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |standard|
        csv << standard.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :projects

end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :projects
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :rememberable,
         :trackable, :validatable

  validates_confirmation_of :password

  mount_uploader :featured_image, ResourceUploader
  has_many :projects

  def full_name
    first_name + ' ' + last_name
  end

  def projects_drafted
    projects.where(status: 0)
  end

  def projects_published
    projects.where(status: 2)
  end

  def projects_pending_review
    projects.where(status: 1)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if params[:search]
      if Rails.env.development?
        @projects = Project.search do
          fulltext "#{params[:search][:terms]}" do
            phrase_fields :name => 2.0
            phrase_slop  1
          end
        end
        @projects = @projects.results
      else
      end
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @current_page = "TAGS"
    @tags = Tag.all
    respond_with(@tags)
  end

  def show
    respond_with(@tag)
  end

  def new
    @current_page = "ADD TAG"
    @tag = Tag.new
    respond_with(@tag)
  end

  def edit
    @current_page = "ADD TAG"
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save
    respond_with(@tag)
  end

  def update
    @tag.update(tag_params)
    respond_with(@tag)
  end

  def destroy
    @tag.destroy
    respond_with(@tag)
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @types = Type.all
    respond_with(@types)
  end

  def show
    respond_with(@type)
  end

  def new
    @current_page = "ADD TYPE"
    @type = Type.new
    respond_with(@type)
  end

  def edit
    @current_page = "EDIT TYPE"
  end

  def create
    @type = Type.new(type_params)
    @type.save
    respond_with(@type)
  end

  def update
    @type.update(type_params)
    respond_with(@type)
  end

  def destroy
    @type.destroy
    respond_with(@type)
  end

  private
    def set_type
      @type = Type.find(params[:id])
    end

    def type_params
      params.require(:type).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      :success => 'alert-success',
      :error => 'alert-danger',
      :alert => 'alert-warning',
      :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to(name, '#', class: 'add_fields', data: { id: id, fields: fields.gsub("\n", "")})
  end

  def link_to_add_project_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to(name, '#', class: 'add-proj-field', data: { id: id, fields: fields.gsub("\n", "")})
  end

  def link_to_add_slider(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to(name, '#', class: 'add-slider', data: { id: id, fields: fields.gsub("\n", "")})
  end

end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/login_events_helper.rb
module LoginEventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/types/_form.html.erb
<%= simple_form_for(@type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<div class="content">
  <!--Panel Content-->
  <div class="page-content">
    <h1 class="page-title">Editing type</h1>
    <div class="clearfix"></div>
    <%= simple_form_for(@type) do |f| %>
    <%= f.error_notification %>
    <div class="edit-type-panel">
        <div class="row">
          <div class="col-xs-12 col-md-6 form-left">
            <div class="form-group">
              <label>NAME</label>
              <%= f.input :name, label: false, input_html: {class: 'form-control'}%>
            </div>
          </div>
          <div class="col-xs-12">
            <%= f.button :submit , 'UPDATE TYPE', class: 'btn btn-primary'%>
          </div>
          <div class="col-xs-12 button-navigation">
            <%= link_to 'SHOW', @type, {class: 'btn btn-info'} %>
            <%= link_to 'BACK', types_path, {class: 'btn btn-warning'} %>
          </div>
        </div>
    </div>
    <% end %>
  </div>
  <!--/.Panel Content-->
</div>

app/views/types/index.html.erb
<div class="content">
  <div class="page-content">
    <h1 class="page-title">Problem Types</h1>
    <div class="clearfix"></div>
    <div class="problem-types-panel">
      <div class="table-responsive">
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th class="text-center" style="width:50px;">#</th>
              <th>Name</th>
              <th style="width:120px;">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @types.each_with_index do |type, i| %>
            <tr>
              <td class="text-center"><%= i + 1 %></td>
              <td><%= type.name %></td>
              <td>
                <% if current_user.admin? %>
                  <!-- show -->
                  <%= link_to type, {class: 'btn btn-sm btn-info'} do %>
                    <i class="fa fa-eye"></i>
                  <% end %>
                  <!-- edit -->
                  <%= link_to edit_type_path(type), {class: 'btn btn-sm btn-info'} do %>
                    <i class="fa fa-pencil"></i>
                  <% end %>
                  <!-- Destroy -->
                  <%= link_to type, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="box-new-type">
        <%= link_to 'NEW TYPE', new_type_path, {class: 'btn btn-md btn-primary'} if current_user.admin? %>
      </div>
    </div>
  </div>
</div>

app/views/types/new.html.erb
<div class="content">
  <!--Panel Content-->
  <div class="page-content">
    <h1 class="page-title">New Type</h1>
    <div class="clearfix"></div>
    <%= simple_form_for(@type) do |f| %>
    <%= f.error_notification %>
    <div class="edit-type-panel">
        <div class="row">
          <div class="col-xs-12 col-md-6 form-left">
            <div class="form-group">
              <label>NAME</label>
              <%= f.input :name, label: false, input_html: {class: 'form-control'}%>
            </div>
          </div>
          <div class="col-xs-12">
            <%= f.button :submit , 'CREATE TYPE', class: 'btn btn-primary'%>
          </div>
          <div class="col-xs-12 button-navigation">
            <%= link_to 'SHOW', @type, {class: 'btn btn-info'} %>
            <%= link_to 'BACK', types_path, {class: 'btn btn-warning'} %>
          </div>
        </div>
    </div>
    <% end %>
  </div>
  <!--/.Panel Content-->
</div>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>
<div class="content">
  <!--Panel Content-->
  <div class="page-content">
    <!--<h1 class="page-title">Editing type</h1>-->
    <div class="clearfix"></div>
    <div class="box-problem-types-show">
      <p class="text-row">
        <span class="text-bold">NAME:</span>
        <span class="text-regular"><%= @type.name %></span>
      </p>
      <div class="row">
        <div class="col-xs-12 button-navigation">
          <%= link_to 'EDIT', edit_type_path(@type), {class: 'btn btn-info'} %>
          <%= link_to 'BACK', types_path, {class: 'btn btn-warning'} %>
        </div>
      </div>

    </div>
  </div>
  <!--/.Panel Content-->
</div>