config/routes.rb
Rails.application.routes.draw do

  # get 'errors/not_found'
  # get 'errors/internal_server_error'
  # get "/404" => "errors#not_found"
  # get "/500" => "errors#internal_server_error"

  resources :login_events

  resources :project_attachment_types

  resources :standards do
    collection { post :import }
  end

  resources :project_attachments

  resources :slider_objects

  resources :tags

  resources :types

  devise_for :users, controllers: { sessions: "users/sessions" }, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
    end

  resources :users

  root 'pages#home'

  match '/auth/:provider/callback', :to => 'sessions#callback', :via => [:get]

  resources :projects

  mathjax 'mathjax'

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :rememberable,
         :trackable, :validatable

  validates_confirmation_of :password

  mount_uploader :featured_image, ResourceUploader
  has_many :projects

  def full_name
    first_name + ' ' + last_name
  end

  def projects_drafted
    projects.where(status: 0)
  end

  def projects_published
    projects.where(status: 2)
  end

  def projects_pending_review
    projects.where(status: 1)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def create
    super do |resource|
      login_event = LoginEvent.create(user_id: resource.id)
      puts login_event
    end
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize_admin!, except: [:show, :edit]
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    #redirect if not user's page or user not admin
  end

  def new
    @user = User.new
    @generated_password = Devise.friendly_token.first(8)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def create
    @current_page = "ADD USER"
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, flash: { success: 'User was successfully created.' } }
        format.js
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @current_page = "EDIT USER"
    @user = User.find(params[:id])

    redirect_to root_url, error: 'You can only edit your page.' unless user_admin_auth ||current_user == @user
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    respond_to do |format|
      unless params[:user][:password] && params[:user][:password] != params[:user][:password_confirmation]
        if @user.update_attributes(user_params)
          format.html { redirect_to @user, flash: { success: 'User was successfully updated.' } }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to edit_user_path(@user), flash: { error: 'Your password does not match the password confirmation.' } }
      end
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end

    def user_admin_auth
      current_user && (current_user == @user || current_user.admin?)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="content">
  <!--Panel Content-->
  <div class="page-content">
    <h1 class="page-title">Edit your profile</h1>
    <div class="clearfix"></div>
    <%= simple_form_for @user do |f| %>
    <div class="edit-profile-panel">
        <div class="row">
          <div class="col-xs-12 col-md-6 form-left">
            <div class="form-group">
              <label>FIRST NAME</label>
              <%= f.input :first_name, label: false, input_html: { class: 'form-control'} %>
            </div>
            <div class="form-group">
              <label>LAST NAME</label>
              <%= f.input :last_name, label: false, input_html: { class: 'form-control'} %>
            </div>
            <div class="form-group">
              <label>EMAIL</label>
              <%= f.input :email, label: false, input_html: { class: 'form-control'} %>
            </div>
          </div>
          <div class="col-xs-12 col-md-6 form-right">
            <div class="form-group">
              <label>PASSWORD</label>
              <%= f.input :password, label: false, placeholder: 'leave blank if not changing', input_html: { class: 'form-control'} %>
            </div>
            <div class="form-group">
              <label>PASSWORD CONFIRMATION</label>
              <%= f.input :password_confirmation, label: false, placeholder: 'leave blank if not changing', input_html: { class: 'form-control'} %>
            </div>
          </div>
          <div class="col-xs-12">
            <%= f.button :submit, 'UPDATE', class: "btn btn-primary" unless @edit %>
          </div>
        </div>
    </div>
    <% end %>
  </div>
  <!--/.Panel Content-->
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class='container' style='margin-top:5%;'>
  <h1>Add A User</h1>

  <%= simple_form_for @user do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
      <%= f.input :password, as: :hidden, input_html: { value: @generated_password } %>
    <%= f.button :submit, 'Create User' %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="content profile-page">
  <div class="box-profile-information">
    <div class="content-box">
      <h1 class="profile-caption"><%= @user.full_name %></h1>
      <%= link_to 'ADD A PROBLEM', new_project_path, class: 'btn btn-primary' %>
      <% if current_user && current_user == @user %>
      <%= link_to "EDIT ACCOUNT", edit_user_path, class: 'btn btn-primary' %>
      <% end %>
      <div class="btn-group">
        <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" type="button">OTHER STUFF
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-menu">
          <%= link_to 'STANDARDS', standards_path, class: 'btn btn-primary' %>
          <%= link_to 'PROBLEM TYPES', types_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
  <!--/.Box - Profile Info-->
  <!--Box - Problem Status-->
  <div class="box-problem-description box-green">
    <div class="title-container">
      <span class="title-icon">
        <i class="fa fa-star-o"></i>
      </span>
      <h2 class="title-text">Published</h2>
    </div>
    <div class="problem-description">
      <div class="problem-description-content">
        <div class="content-panel">
          <ul class="list-unstyled fa-ul list-problems">
            <% @user.projects_published.each do |project| %>
            <li><%= link_to project do %>
              <i class="fa-li fa fa-circle-o"></i><%= project.name %>
              <% end %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!--/.Box - Problem Status-->
  <% unless Project.pending_review.empty? %>
  <div class="box-problem-description box-orange">
    <div class="title-container">
      <span class="title-icon">
        <i class="fa fa-file-text-o"></i>
      </span>
      <h2 class="title-text">Pending Review</h2>
    </div>
    <div class="problem-description">
      <div class="problem-description-content">
        <div class="content-panel">
          <ul class="list-unstyled fa-ul list-problems">
            <% Project.pending_review.each do |project| %>
            <li><%= link_to project do %>
              <i class="fa-li fa fa-circle-o"></i><%= project.name %>
              <% end %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <!--Box - Problem Status-->
  <div class="box-problem-description box-blue">
    <div class="title-container">
      <span class="title-icon">
        <i class="fa fa-file-text-o"></i>
      </span>
      <h2 class="title-text">Drafts</h2>
    </div>
    <div class="problem-description">
      <div class="problem-description-content">
        <div class="content-panel">
          <ul class="list-unstyled fa-ul list-problems">
            <% @user.projects_drafted.each do |project| %>
              <li><%= link_to project do %>
                <i class="fa-li fa fa-circle-o"></i><%= project.name %>
                <% end %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>