config/routes.rb
Rails.application.routes.draw do

  # get 'errors/not_found'
  # get 'errors/internal_server_error'
  # get "/404" => "errors#not_found"
  # get "/500" => "errors#internal_server_error"

  resources :login_events

  resources :project_attachment_types

  resources :standards do
    collection { post :import }
  end

  resources :project_attachments

  resources :slider_objects

  resources :tags

  resources :types

  devise_for :users, controllers: { sessions: "users/sessions" }, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
    end

  resources :users

  root 'pages#home'

  match '/auth/:provider/callback', :to => 'sessions#callback', :via => [:get]

  resources :projects

  mathjax 'mathjax'

end

app/models/slider_object.rb
class SliderObject < ActiveRecord::Base
  mount_uploader :resource, ResourceUploader

  belongs_to :project

  before_save :default_name

  def default_name
    self.file_name = File.basename(resource.file.path, '.*').gsub("_", " ") if resource.file
  end

  def mark_for_removal
    unless resource
      mark_for_destruction
    end
  end
end

app/models/slider_objects.rb
class SliderObject < ActiveRecord::Base
  mount_uploader :resource, ResourceUploader

  belongs_to :project
  before_save :default_name

  def default_name
    self.file_name = File.basename(resource.file.path, '.*').gsub("_", " ")
  end

  def mark_for_removal
    unless resource
      mark_for_destruction
    end
  end

end

app/controllers/slider_objects_controller.rb
class SliderObjectsController < ApplicationController
  before_action :set_slider_object, only: [:show, :edit, :update, :destroy]

  def index
    @slider_objects = SliderObject.all
    respond_with(@slider_objects)
  end

  def show
    respond_with(@slider_object)
  end

  def new
    @slider_object = SliderObject.new
    respond_with(@slider_object)
  end

  def edit
  end

  def create
    @slider_object = SliderObject.new(slider_object_params)
    @slider_object.save
    respond_with(@slider_object)
  end

  def update
    @slider_object.update(slider_object_params)
    respond_with(@slider_object)
  end

  def destroy
    @slider_object.destroy
    respond_with(@slider_object)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slider_object
      @slider_object = SliderObject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slider_object_params
      params[:slider_object]
      params.require(:slider_objects).permit(:project_id, :resource, :position, :_destroy, :description, :order)
    end
end

app/helpers/slider_objects_helper.rb
module SliderObjectsHelper
end

app/views/slider_objects/_form.html.erb
<%= simple_form_for(@slider_object) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/slider_objects/edit.html.erb
<h1>Editing slider_object</h1>

<%= render 'form' %>

<%= link_to 'Show', @slider_object %> |
<%= link_to 'Back', slider_objects_path %>

app/views/slider_objects/index.html.erb
<h1>Listing slider_objects</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slider_objects.each do |slider_object| %>
      <tr>
        <td><%= link_to 'Show', slider_object %></td>
        <td><%= link_to 'Edit', edit_slider_object_path(slider_object) %></td>
        <td><%= link_to 'Destroy', slider_object, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slider object', new_slider_object_path %>

app/views/slider_objects/new.html.erb
<h1>New slider_object</h1>

<%= render 'form' %>

<%= link_to 'Back', slider_objects_path %>

app/views/slider_objects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_slider_object_path(@slider_object) %> |
<%= link_to 'Back', slider_objects_path %>